-- =====================================================================
-- init.sql — PostgreSQL initialization for the multi-tier capstone app
-- =====================================================================
--
-- Creates the database, an application role, the schema, and seed data.
--
-- HOW IT RUNS:
--   * Docker Compose: mount this into the Postgres container at
--       /docker-entrypoint-initdb.d/init.sql
--     The official postgres image runs every .sql there ONCE, on first
--     init of an empty data directory (i.e. first `up` on a fresh volume).
--   * Vagrant / bare VM: run it as the postgres superuser, e.g.
--       sudo -u postgres psql -f /path/to/init.sql
--
-- IMPORTANT — matches the app:
--   The Spring app connects as DB_USER / DB_PASSWORD to DB_NAME
--   (defaults: appuser / changeme / appdb — see application.properties).
--   Keep these in sync with your .env / tfvars. Change the password below
--   AND in your environment; don't ship "changeme" to the cloud.
--
--   The app runs Hibernate with ddl-auto=update, so it will also ensure
--   the table exists at boot. The CREATE TABLE below is written to be
--   compatible with what Hibernate generates for the Note entity
--   (BIGINT identity PK + text content), so the two do not conflict.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Role (application user)
-- ---------------------------------------------------------------------
-- Guarded so re-running doesn't error if the role already exists.
DO
$$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'appuser') THEN
        CREATE ROLE appuser WITH LOGIN PASSWORD 'appuser123';
    END IF;
END
$$;


-- ---------------------------------------------------------------------
-- 2. Database
-- ---------------------------------------------------------------------
-- CREATE DATABASE can't run inside the DO block above (no transaction),
-- and can't use IF NOT EXISTS. In the Docker entrypoint the DB named by
-- POSTGRES_DB already exists, so this section is mainly for the bare-VM
-- path. The \gexec trick creates it only if missing.
SELECT 'CREATE DATABASE appdb OWNER appuser'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'appdb')\gexec


-- ---------------------------------------------------------------------
-- 3. Connect to the app database for the rest of the script
-- ---------------------------------------------------------------------
\connect appdb


-- ---------------------------------------------------------------------
-- 4. Schema — the note table
-- ---------------------------------------------------------------------
-- BIGINT identity column matches Hibernate's GenerationType.IDENTITY.
CREATE TABLE IF NOT EXISTS note (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255)
);


-- ---------------------------------------------------------------------
-- 5. Privileges
-- ---------------------------------------------------------------------
-- Make sure the app role owns / can use everything in the public schema.
ALTER DATABASE appdb OWNER TO appuser;
GRANT ALL PRIVILEGES ON SCHEMA public TO appuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO appuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO appuser;
ALTER TABLE note OWNER TO appuser;


-- ---------------------------------------------------------------------
-- 6. Seed data
-- ---------------------------------------------------------------------
-- Only insert if the table is empty, so re-runs don't pile up duplicates.
INSERT INTO note (content)
SELECT * FROM (VALUES
    ('First seeded note — the database is wired up.'),
    ('Second seeded note — try GET /notes/count.'),
    ('Third seeded note — POST /notes to add more.')
) AS seed(content)
WHERE NOT EXISTS (SELECT 1 FROM note);


-- Keep the identity sequence ahead of the seeded rows so the app's next
-- insert doesn't collide with a seeded id.
SELECT setval(
    pg_get_serial_sequence('note', 'id'),
    COALESCE((SELECT MAX(id) FROM note), 1)
);
